package org.simpleflatmapper.map.property;



public class AutoGeneratedProperty {

    public static final AutoGeneratedProperty DEFAULT = new AutoGeneratedProperty();

    private AutoGeneratedProperty() {
        
    }

    @Override
    public String toString() {
        return "AutoGeneratedProperty{}";
    }

}
