package org.simpleflatmapper.map.property;



public class IgnoreAutoGeneratedProperty {

    public static final IgnoreAutoGeneratedProperty DEFAULT = new IgnoreAutoGeneratedProperty();

    private IgnoreAutoGeneratedProperty() {
        
    }

    @Override
    public String toString() {
        return "IgnoreAutoGeneratedProperty{}";
    }

}
