/*
 * This file is generated by jOOQ.
 */
package org.simpleflatmapper.jooq.test.books;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookRecord extends UpdatableRecordImpl<BookRecord> implements Record5<Integer, Integer, String, Integer, Timestamp> {

    private static final long serialVersionUID = 1125902110;

    /**
     * Setter for <code>PUBLIC.BOOK.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.BOOK.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.BOOK.AUTHOR_ID</code>.
     */
    public void setAuthorId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.BOOK.AUTHOR_ID</code>.
     */
    public Integer getAuthorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.BOOK.TITLE</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.BOOK.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.BOOK.PUBLISHED_IN</code>.
     */
    public void setPublishedIn(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.BOOK.PUBLISHED_IN</code>.
     */
    public Integer getPublishedIn() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.BOOK.REC_TIMESTAMP</code>.
     */
    public void setRecTimestamp(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.BOOK.REC_TIMESTAMP</code>.
     */
    public Timestamp getRecTimestamp() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, Integer, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, Integer, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Book.BOOK.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Book.BOOK.AUTHOR_ID;
    }

    @Override
    public Field<String> field3() {
        return Book.BOOK.TITLE;
    }

    @Override
    public Field<Integer> field4() {
        return Book.BOOK.PUBLISHED_IN;
    }

    @Override
    public Field<Timestamp> field5() {
        return Book.BOOK.REC_TIMESTAMP;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAuthorId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public Integer component4() {
        return getPublishedIn();
    }

    @Override
    public Timestamp component5() {
        return getRecTimestamp();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAuthorId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public Integer value4() {
        return getPublishedIn();
    }

    @Override
    public Timestamp value5() {
        return getRecTimestamp();
    }

    @Override
    public BookRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BookRecord value2(Integer value) {
        setAuthorId(value);
        return this;
    }

    @Override
    public BookRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public BookRecord value4(Integer value) {
        setPublishedIn(value);
        return this;
    }

    @Override
    public BookRecord value5(Timestamp value) {
        setRecTimestamp(value);
        return this;
    }

    @Override
    public BookRecord values(Integer value1, Integer value2, String value3, Integer value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(Integer id, Integer authorId, String title, Integer publishedIn, Timestamp recTimestamp) {
        super(Book.BOOK);

        set(0, id);
        set(1, authorId);
        set(2, title);
        set(3, publishedIn);
        set(4, recTimestamp);
    }
}
